-- Payment Limit Monitoring System Database Schema
-- Oracle Database DDL

-- SETTLEMENT table
-- Stores the latest version of each settlement transaction
CREATE TABLE SETTLEMENT (
    ID NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SETTLEMENT_ID VARCHAR2(100) NOT NULL,
    SETTLEMENT_VERSION NUMBER(19) NOT NULL,
    PTS VARCHAR2(50) NOT NULL,
    PROCESSING_ENTITY VARCHAR2(50) NOT NULL,
    COUNTERPARTY_ID VARCHAR2(100) NOT NULL,
    VALUE_DATE DATE NOT NULL,
    CURRENCY VARCHAR2(3) NOT NULL,
    AMOUNT NUMBER(18,2) NOT NULL,
    BUSINESS_STATUS VARCHAR2(20) NOT NULL,
    DIRECTION VARCHAR2(10) NOT NULL,
    GROSS_NET VARCHAR2(10) NOT NULL,
    IS_OLD NUMBER(1) DEFAULT 0,
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_direction CHECK (DIRECTION IN ('PAY', 'RECEIVE')),
    CONSTRAINT chk_type CHECK (GROSS_NET IN ('GROSS', 'NET')),
    CONSTRAINT chk_business_status CHECK (BUSINESS_STATUS IN ('PENDING', 'INVALID', 'VERIFIED', 'CANCELLED')),
    CONSTRAINT chk_is_old CHECK (IS_OLD IN (0, 1))
);

-- Indexes for performance
CREATE INDEX idx_settlement_lookup ON SETTLEMENT(SETTLEMENT_ID, PTS, PROCESSING_ENTITY);
CREATE INDEX idx_settlement_group ON SETTLEMENT(PTS, PROCESSING_ENTITY, COUNTERPARTY_ID, VALUE_DATE);
CREATE INDEX idx_settlement_version ON SETTLEMENT(SETTLEMENT_ID, SETTLEMENT_VERSION);
CREATE INDEX idx_settlement_direction_status ON SETTLEMENT(DIRECTION, BUSINESS_STATUS);

-- SETTLEMENT_HIST table
-- Stores old versions of settlements (archived daily)
CREATE TABLE SETTLEMENT_HIST (
    ID NUMBER(19) PRIMARY KEY,
    SETTLEMENT_ID VARCHAR2(100) NOT NULL,
    SETTLEMENT_VERSION NUMBER(19) NOT NULL,
    PTS VARCHAR2(50) NOT NULL,
    PROCESSING_ENTITY VARCHAR2(50) NOT NULL,
    COUNTERPARTY_ID VARCHAR2(100) NOT NULL,
    VALUE_DATE DATE NOT NULL,
    CURRENCY VARCHAR2(3) NOT NULL,
    AMOUNT NUMBER(18,2) NOT NULL,
    BUSINESS_STATUS VARCHAR2(20) NOT NULL,
    DIRECTION VARCHAR2(10) NOT NULL,
    GROSS_NET VARCHAR2(10) NOT NULL,
    IS_OLD NUMBER(1) DEFAULT 1,
    CREATE_TIME TIMESTAMP,
    UPDATE_TIME TIMESTAMP,
    ARCHIVE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_hist_lookup ON SETTLEMENT_HIST(SETTLEMENT_ID, SETTLEMENT_VERSION);
CREATE INDEX idx_hist_pts ON SETTLEMENT_HIST(PTS, PROCESSING_ENTITY);

-- EXCHANGE_RATE table
-- Stores latest exchange rates for currency conversion
CREATE TABLE EXCHANGE_RATE (
    CURRENCY VARCHAR2(3) PRIMARY KEY,
    RATE_TO_USD NUMBER(12,6) NOT NULL,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_exchange_rate_update ON EXCHANGE_RATE(UPDATE_TIME);

-- RUNNING_TOTAL table
-- Stores aggregated exposure data per group
CREATE TABLE RUNNING_TOTAL (
    ID NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PTS VARCHAR2(50) NOT NULL,
    PROCESSING_ENTITY VARCHAR2(50) NOT NULL,
    COUNTERPARTY_ID VARCHAR2(100) NOT NULL,
    VALUE_DATE DATE NOT NULL,
    RUNNING_TOTAL NUMBER(18,2) DEFAULT 0,
    REF_ID NUMBER(19) NOT NULL,
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_running_total UNIQUE(PTS, PROCESSING_ENTITY, COUNTERPARTY_ID, VALUE_DATE)
);

CREATE INDEX idx_running_total_lookup ON RUNNING_TOTAL(PTS, PROCESSING_ENTITY, COUNTERPARTY_ID, VALUE_DATE);

-- ACTIVITIES table
-- Audit trail for approval workflow and system actions
CREATE TABLE ACTIVITIES (
    ID NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PTS VARCHAR2(50),
    PROCESSING_ENTITY VARCHAR2(50),
    SETTLEMENT_ID VARCHAR2(100) NOT NULL,
    SETTLEMENT_VERSION NUMBER(19) NOT NULL,
    USER_ID VARCHAR2(100) NOT NULL,
    USER_NAME VARCHAR2(200),
    ACTION_TYPE VARCHAR2(50) NOT NULL,
    ACTION_COMMENT VARCHAR2(500),
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_activities_settlement ON ACTIVITIES(SETTLEMENT_ID, SETTLEMENT_VERSION);
CREATE INDEX idx_activities_user ON ACTIVITIES(USER_ID, CREATE_TIME);
CREATE INDEX idx_activities_action ON ACTIVITIES(ACTION_TYPE, CREATE_TIME);

-- NOTIFICATION_QUEUE table
-- Queue for external system notifications with retry mechanism
CREATE TABLE NOTIFICATION_QUEUE (
    ID NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SETTLEMENT_ID VARCHAR2(100) NOT NULL,
    STATUS VARCHAR2(50) NOT NULL,
    PAYLOAD CLOB,
    RETRY_COUNT NUMBER(5) DEFAULT 0,
    NEXT_RETRY_TIME TIMESTAMP,
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_notification_status CHECK (STATUS IN ('PENDING', 'SENT', 'FAILED'))
);

CREATE INDEX idx_notification_status_retry ON NOTIFICATION_QUEUE(STATUS, NEXT_RETRY_TIME);
CREATE INDEX idx_notification_settlement ON NOTIFICATION_QUEUE(SETTLEMENT_ID);

-- Sequence for manual ID generation (if needed)
CREATE SEQUENCE settlement_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE activity_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE running_total_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE notification_seq START WITH 1 INCREMENT BY 1;

-- Comments for documentation
COMMENT ON TABLE SETTLEMENT IS 'Latest version of each settlement transaction';
COMMENT ON COLUMN SETTLEMENT.ID IS 'Auto-incrementing sequence ID (REF_ID)';
COMMENT ON COLUMN SETTLEMENT.SETTLEMENT_ID IS 'Business settlement identifier';
COMMENT ON COLUMN SETTLEMENT.SETTLEMENT_VERSION IS 'Version timestamp from external system';
COMMENT ON COLUMN SETTLEMENT.IS_OLD IS 'Flag for old versions (0=newest, 1=old)';
COMMENT ON COLUMN SETTLEMENT.BUSINESS_STATUS IS 'PENDING, INVALID, VERIFIED, or CANCELLED';

COMMENT ON TABLE SETTLEMENT_HIST IS 'Archived old versions of settlements';

COMMENT ON TABLE EXCHANGE_RATE IS 'Latest exchange rates for USD conversion';

COMMENT ON TABLE RUNNING_TOTAL IS 'Aggregated exposure per group (PTS, PE, Counterparty, Value Date)';
COMMENT ON COLUMN RUNNING_TOTAL.REF_ID IS 'Sequence ID used for this calculation';

COMMENT ON TABLE ACTIVITIES IS 'Audit trail for approval workflow';
COMMENT ON COLUMN ACTIVITIES.ACTION_TYPE IS 'REQUEST_RELEASE, AUTHORISE, or other actions';

COMMENT ON TABLE NOTIFICATION_QUEUE IS 'External notifications with retry mechanism';
